import { Ubuntu } from "next/font/google";
import "@/styles/globals.css";

const ubuntu = Ubuntu({ 
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"] 
});

export const metadata = {
  title: "opiniON",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        {children}
      </body>
    </html>
  );
}
